-- source file: /home/dima/swdb/swdb_all_data/swdb_all_data_unziped/USA_aod_2020_RDFv4.1/ACCOUNTS/ACCOUNTS.txt
-- region: USA, year: 2020

CREATE TABLE usa_2020_rdf_accounts (
    account_id                    text,
    account_name                  text,
    account_trade_name            text,
    account_street1               text,
    account_street2               text,
    account_city                  text,
    account_postal_state          text,
    account_postal_code           text,
    account_country               text,
    account_phone                 text,
    account_fax                   text,
    account_url                   text,
    account_employees             text,
    account_it_employees          text,
    account_revenue_usd           text,
    account_revenue_euros         text,
    account_revenue_pounds        text,
    account_ict_spending          text,
    account_hw_spending           text,
    account_sw_spending           text,
    account_it_comnet_spending    text,
    account_it_services_spending  text,
    account_it_staff_spending     text,
    account_telco_spending        text,
    account_nb_sites              text,
    account_nb_countries          text,
    account_pri_naics6_code       text,
    account_sec_naics6_code       text,
    account_pri_sic4_code         text,
    account_sec_sic4_code         text,
    account_nace4_code            text,
    account_continent             text,
    account_country_grouping_code text,
    account_country_code          text,
    account_region                text,
    account_subregion             text,
    account_state                 text,
    account_county                text,
    account_servers               text,
    account_workstations          text,
    account_pcs                   text,
    account_desktops              text,
    account_laptops               text,
    account_tablets               text,
    account_printers              text,
    account_storage               text,
    account_aod_url               text
);