-- source file: /home/dima/swdb/swdb_all_data/swdb_all_data_unziped/USA_2002/Hist2002_CORPTOTALS.txt
-- region: USA, year: 2002

CREATE TABLE usa_2002_hist2002_corptotals (
    corpid        text,
    csystems      text,
    ctotdasd      text,
    ctotstorage   text,
    ctotnodes     text,
    ctotmain      text,
    ctotibmpcm    text,
    ctotmidr      text,
    ctotas400     text,
    ctotwks       text,
    ctotserver    text,
    ctotlansvr    text,
    ctotinsvr     text,
    ctotpcsvr     text,
    ctotpc        text,
    ctotdesk      text,
    ctotport      text,
    ctotext       text,
    ctotlan       text,
    ctotddd       text,
    ctott1        text,
    ctotdata      text,
    ctottrunk     text,
    ctotldexp     text,
    ctotups       text,
    ctotplanpc    text,
    ctotplansvr   text,
    ctotplanphone text,
    ctotisdn      text,
    ctot800       text,
    cdatgt56k     text
);