-- source file: /home/dima/swdb/swdb_all_data/swdb_all_data_unziped/USA_2000/Hist2000_COMM.txt
-- region: USA, year: 2000

CREATE TABLE usa_2000_hist2000_comm (
    siteid           text,
    commdate         text,
    telesyspurch     text,
    longdispurch     text,
    totext           text,
    callcenter       text,
    telecallers      text,
    pbxstatus        text,
    coswstatus       text,
    centrexstatus    text,
    keystatus        text,
    singlnestatus    text,
    unspphnstatus    text,
    ldexp            text,
    ldout            text,
    ldin             text,
    ldintl           text,
    lddom            text,
    ldoutexp         text,
    ldinexp          text,
    ldtotintexp      text,
    ldtotdomexp      text,
    remotes          text,
    tottrunk         text,
    totddd           text,
    tot800           text,
    tottie           text,
    tottiepriv       text,
    tottieded        text,
    totisdn          text,
    tott1            text,
    tott3            text,
    totxdsl          text,
    totdata          text,
    maxdatacom       text,
    totcell          text,
    privnet_status   text,
    vpn_status       text,
    netpurch         text,
    remotes_in_cntry text
);