-- source file: /home/dima/swdb/swdb_all_data/swdb_all_data_unziped/USA_2007/Hist2007_corptotals.txt
-- region: USA, year: 2007

CREATE TABLE usa_2007_hist2007_corptotals (
    corpid              text,
    ctotstorage         text,
    ctotserver          text,
    cplanserver         text,
    ctotibmpcm          text,
    ctotibmmidrange     text,
    ctotintelamdsvr     text,
    ctotunixriscsvr     text,
    ctotothpropsvr      text,
    ctotwks             text,
    ctotpc              text,
    cplanpc             text,
    ctotdesk            text,
    ctotport            text,
    ctotapple           text,
    ctotext             text,
    ctotddd             text,
    ctott1              text,
    ctott3              text,
    ctotocx             text,
    ctotxdsl            text,
    ctotisdn            text,
    ctotldexp           text,
    cplanphone          text,
    ctot800             text,
    ctottie             text,
    ctotups             text,
    ctotprt             text,
    cplanprt            text,
    ctotprodprt         text,
    ctotcolorprt        text,
    ctotlaserprt        text,
    ctotinkjetprt       text,
    ctotdotmatrixprt    text,
    ctotwideformprt     text,
    ctotmultiprt        text,
    ctotcopier          text,
    ctotnodes           text,
    ctotwireless_users  text,
    cplanwireless_users text,
    ctotrouter          text,
    ctotlansw           text
);