-- source file: /home/dima/swdb/swdb_all_data/swdb_all_data_unziped/USA_2007/Hist2007_triggers.txt
-- region: USA, year: 2007

CREATE TABLE usa_2007_hist2007_triggers (
    siteid            text,
    dir_change        text,
    ceo_change        text,
    est_itbudgetchg   text,
    virtualserver     text,
    compliancetrckng  text,
    voiceoverip       text,
    virtualstorage    text,
    opensource        text,
    soaimplementation text,
    wanacceleration   text,
    securityupgrades  text,
    powerconsumption  text,
    plan50000         text,
    pctrendchange     text,
    svrtrendchange    text,
    prttrendchange    text,
    t1trendchange     text,
    storagecapchg     text,
    acctgvendorchg    text,
    cellvendorchg     text,
    crmvendorchg      text,
    dbmsvendorchg     text,
    deskvendorchg     text,
    grpwvendorchg     text,
    ldcvendorchg      text,
    netlnvendorchg    text,
    langvendorchg     text,
    oprvendorchg      text,
    pbxvendorchg      text,
    portvendorchg     text,
    storvendorchg     text,
    svrvendorchg      text,
    prefdeskchg       text,
    prefportchg       text,
    prefsvrchg        text,
    deskloyaltychg    text,
    portloyaltychg    text,
    svrloyaltychg     text,
    planmove          text,
    datacentermove    text,
    offshorelabor     text,
    trigger_presence  text
);