-- source file: /home/dima/swdb/swdb_all_data/swdb_all_data_unziped/USA_2011/Hist2011_ENTERPRISE.txt
-- region: USA, year: 2011

CREATE TABLE usa_2011_hist2011_enterprise (
    siteid                    text,
    ent_id                    text,
    ent_company               text,
    corphdq                   text,
    multinational             text,
    ent_country               text,
    ent_type                  text,
    ent_rank                  text,
    ent_alttype               text,
    ent_altrank               text,
    ent_emple                 text,
    ent_emple_discrete        text,
    ent_reven                 text,
    ent_reven_discrete        text,
    ent_it_emple              text,
    ent_pc                    text,
    ent_desktop               text,
    ent_laptop                text,
    ent_server                text,
    ent_printer               text,
    ent_storage               text,
    ent_extensions            text,
    ent_wireless_users        text,
    ent_internet_users        text,
    ent_networklines          text,
    ent_it_budget             text,
    ent_hardware_budget       text,
    ent_pc_budget             text,
    ent_server_budget         text,
    ent_terminal_budget       text,
    ent_printer_budget        text,
    ent_other_hardware_budget text,
    ent_storage_budget        text,
    ent_comm_budget           text,
    ent_software_budget       text,
    ent_services_budget       text,
    ent_reven_sort            text,
    ent_emple_sort            text
);