-- source file: /home/dima/swdb/swdb_all_data/swdb_all_data_unziped/USA_2006/Hist2006_corp.txt
-- region: USA, year: 2006

CREATE TABLE usa_2006_hist2006_corp (
    corpid            text,
    europe_corpid     text,
    ccompany          text,
    ccompanydba       text,
    caddress          text,
    cstreet           text,
    cstreet2          text,
    ccity             text,
    cstate            text,
    czipcode          text,
    ccountry          text,
    ccountrycode      text,
    cphone            text,
    corp_ticker       text,
    exchange          text,
    corptype          text,
    rank              text,
    corpemple         text,
    sales             text,
    cyear             text,
    cfiscl            text,
    csiccode          text,
    cnaics            text,
    cnaics_3desc      text,
    cnaics_6desc      text,
    csites            text,
    ctotsites         text,
    cenhsites         text,
    cmetro            text,
    cmajmetro         text,
    alttype           text,
    altrank           text,
    cdunsi            text,
    cinfousa          text,
    csic2_desc        text,
    corphpurl         text,
    ctotbranch        text,
    ctotdivhq         text,
    icorp             text,
    corp_level        text,
    corp_tdb_flag     text,
    corp_channel_flag text,
    corp_level_sort   text,
    corp_cgroup       text,
    corp_parents      text,
    csicsubgroup      text,
    corptr            text,
    czipsector        text,
    careacode         text,
    csickey           text,
    csic3             text,
    corp_chansites    text
);