-- source file: /home/dima/swdb/swdb_all_data/swdb_all_data_unziped/USA_2014/Hist2014_VPS.txt
-- region: USA, year: 2014

CREATE TABLE usa_2014_hist2014_vps (
    siteid            text,
    adp_vps           text,
    adp_index         text,
    avaya_vps         text,
    avaya_index       text,
    cognos_vps        text,
    cognos_index      text,
    emc_vps           text,
    emc_index         text,
    hyperion_vps      text,
    hyperion_index    text,
    infor_vps         text,
    infor_index       text,
    informatica_vps   text,
    informatica_index text,
    jdedwards_vps     text,
    jdedwards_index   text,
    kronos_vps        text,
    kronos_index      text,
    lawson_vps        text,
    lawson_index      text,
    netapp_vps        text,
    netapp_index      text,
    oracle_vps        text,
    oracle_index      text,
    peoplesoft_vps    text,
    peoplesoft_index  text,
    sage_vps          text,
    sage_index        text,
    salesforce_vps    text,
    salesforce_index  text,
    sap_vps           text,
    sap_index         text,
    siebel_vps        text,
    siebel_index      text,
    spss_vps          text,
    spss_index        text,
    sybase_vps        text,
    sybase_index      text,
    vmware_vps        text,
    vmware_index      text
);