-- source file: /home/dima/swdb/swdb_all_data/swdb_all_data_unziped/USA_2005/Hist2005_corp.txt
-- region: USA, year: 2005

CREATE TABLE usa_2005_hist2005_corp (
    corpid       text,
    ccompany     text,
    cstreet      text,
    ccity        text,
    cstate       text,
    czipcode     text,
    ccountry     text,
    ccountrycode text,
    cphone       text,
    corp_ticker  text,
    exchange     text,
    corptype     text,
    rank         text,
    corpemple    text,
    sales        text,
    cyear        text,
    cfiscl       text,
    csiccode     text,
    cnaics       text,
    cnaic3des    text,
    cnaic6des    text,
    csites       text,
    ctotsites    text,
    cenhsites    text,
    cmetro       text,
    cmajmetro    text,
    alttype      text,
    altrank      text,
    cdunsi       text,
    cinfousa     text,
    csic2des     text,
    corphpurl    text,
    ctotbranch   text,
    ctotdivhq    text,
    csicsubgroup text,
    corptr       text,
    czipsector   text,
    careacode    text,
    csickey      text,
    csic3        text
);