-- source file: /home/dima/swdb/swdb_all_data/swdb_all_data_unziped/USA_2005/Hist2005_corptotals.txt
-- region: USA, year: 2005

CREATE TABLE usa_2005_hist2005_corptotals (
    corpid              text,
    ctotstorage         text,
    ctotserver          text,
    cplanserver         text,
    ctotibmpcm          text,
    ctotibmmidrange     text,
    ctotintelamdsvr     text,
    ctotunixriscsvr     text,
    ctotothpropsvr      text,
    ctotwks             text,
    ctotpc              text,
    cplanpc             text,
    ctotdesk            text,
    ctotport            text,
    ctotapple           text,
    ctotext             text,
    ctotddd             text,
    ctott1              text,
    ctotdata            text,
    ctottrunk           text,
    ctotldexp           text,
    cplanphone          text,
    ctotisdn            text,
    ctot800             text,
    cdatgt56k           text,
    ctotups             text,
    ctotprt             text,
    cplanprt            text,
    ctotprodprt         text,
    ctotcolorprt        text,
    ctotlaserprt        text,
    ctotinkjetprt       text,
    ctotdotmatrixprt    text,
    ctotwideformprt     text,
    ctotmultiprt        text,
    ctotcopier          text,
    ctotnodes           text,
    ctotwireless_users  text,
    cplanwireless_users text,
    ctotrouter          text,
    ctotlansw           text
);