-- source file: /home/dima/swdb/swdb_all_data/swdb_all_data_unziped/USA_2008/Hist2008_dynamic.txt
-- region: USA, year: 2008

CREATE TABLE usa_2008_hist2008_dynamic (
    siteid            text,
    nuts2_code        text,
    nuts2_desc        text,
    nuts3_code        text,
    nuts3_desc        text,
    totunspecsvr      text,
    totnetworkline    text,
    plannetworkline   text,
    totunspecline     text,
    planunspecline    text,
    estitbudget       text,
    estcommbudget     text,
    esthardwarebudget text,
    estsoftwarebudget text,
    eststoragebudget  text,
    estservicesbudget text,
    estitstaffbudget  text,
    clli_code         text,
    estitotherbudget  text,
    replacementratio  text,
    appconsolidation  text,
    naf_code          text,
    contactsdate      text,
    wm_totpc          text,
    wm_totport        text,
    wm_totserver      text,
    wm_totprinter     text,
    wm_totnetworkline text,
    wm_totstorage     text,
    wm_wireless_users text,
    wm_totext         text,
    wm_inetuser       text,
    wm_itstaff        text,
    est_storage       text,
    est_inetuser      text,
    est_it_staff      text
);