-- source file: /home/dima/swdb/swdb_all_data/swdb_all_data_unziped/USA_2008/Hist2008_enterprise.txt
-- region: USA, year: 2008

CREATE TABLE usa_2008_hist2008_enterprise (
    ent_id                text,
    ent_dunsnumber        text,
    ent_company           text,
    ent_address           text,
    ent_address2          text,
    ent_address3          text,
    ent_city              text,
    ent_county_name       text,
    ent_state             text,
    ent_zipcode           text,
    ent_country           text,
    ent_continent_code    text,
    ent_address_mail      text,
    ent_address2_mail     text,
    ent_address3_mail     text,
    ent_city_mail         text,
    ent_state_mail        text,
    ent_country_mail      text,
    ent_zipcode_mail      text,
    ent_access_code       text,
    ent_phone             text,
    ent_hqcountry         text,
    ent_metro             text,
    ent_ticker            text,
    ent_exchange          text,
    ent_type              text,
    ent_rank              text,
    ent_alttype           text,
    ent_altrank           text,
    ent_employees         text,
    ent_sales             text,
    ent_dunssites         text,
    ent_citdbsites        text,
    ent_citdbdatacenters  text,
    ent_citdblargeitsites text,
    ent_siccode           text,
    ent_sic4_desc         text,
    ent_naics             text,
    ent_naics6_desc       text,
    ent_url               text,
    ent_msa_description   text,
    ent_areacode          text,
    ent_zipsector         text,
    ent_zip7              text,
    enterprise_id         text,
    ent_nadunssites       text
);