-- source file: /home/dima/swdb/swdb_all_data/swdb_all_data_unziped/USA_2012/Hist2012_PLS.txt
-- region: USA, year: 2012

CREATE TABLE usa_2012_hist2012_pls (
    siteid                          text,
    laptop_pls                      text,
    workstation_pls                 text,
    desktop_virtualization_pls      text,
    server_pls                      text,
    server_os_pls                   text,
    server_virtualization_pls       text,
    multifunction_printer_pls       text,
    highvolume_printer_pls          text,
    ups_3phase_pls                  text,
    lower_power_consumption_pls     text,
    storage_capacity_expansion_pls  text,
    storage_virtualization_pls      text,
    storage_mgmt_sw_pls             text,
    ucs_pls                         text,
    voip_pls                        text,
    network_line_pls                text,
    wireless_lan_pls                text,
    router_pls                      text,
    vpn_pls                         text,
    network_services_pls            text,
    security_sw_pls                 text,
    enterprise_mgmt_sw_pls          text,
    idaccess_sw_pls                 text,
    erp_sw_pls                      text,
    dbms_pls                        text,
    software_as_a_service_pls       text,
    antivirus_sw_pls                text,
    outsource_sw_services_pls       text,
    cloud_computing_pls             text,
    pcs_pls                         text,
    das_pls                         text,
    nas_pls                         text,
    san_pls                         text,
    compliance_pls                  text,
    windows7_adoption_pls           text,
    asset_mgmt_sw_pls               text,
    doc_mgmt_sw_pls                 text,
    tablet_pls                      text,
    infrastructure_as_a_service_pls text,
    data_loss_prevention_pls        text,
    digital_signage_pls             text,
    messaging_security_pls          text,
    platform_as_a_service_pls       text,
    smartphone_pls                  text
);