-- source file: /home/dima/swdb/swdb_all_data/swdb_all_data_unziped/USA_2009/Hist2009_softserv.txt
-- region: USA, year: 2009

CREATE TABLE usa_2009_hist2009_softserv (
    siteid                 text,
    swupdate               text,
    developers             text,
    pc_unix_status         text,
    pc_linux_status        text,
    svr_unix_status        text,
    svr_linux_status       text,
    svr_opr_status         text,
    hpw_opr_status         text,
    drecover_status        text,
    lansvcs_status         text,
    swsvcs_status          text,
    inetsvcs_status        text,
    wansvcs_status         text,
    hwsvcs_status          text,
    hwmnt_status           text,
    itsource               text,
    opensource             text,
    planopensource         text,
    webservices            text,
    planwebservices        text,
    app_dev_sw_status      text,
    data_mgmt_sw_status    text,
    workflow_sw_status     text,
    ent_sys_sw_status      text,
    security_sw_status     text,
    storage_sw_status      text,
    ent_sw_status          text,
    ind_specific_sw_status text,
    grpware_sw_status      text,
    svr_comp_sw_status     text,
    erp_presence           text,
    bpm_framework          text,
    planbpm_framework      text,
    datawarehouse          text,
    plandatawarehouse      text,
    bus_intel_sw_status    text,
    ecommerce              text,
    planecommerce          text,
    webloc                 text,
    targetaudience         text,
    edi_development        text,
    baacct                 text,
    basales                text,
    bamktg                 text,
    bahr                   text,
    bacc                   text,
    bacust                 text,
    bamanuf                text,
    baeng                  text,
    bapurch                text
);