-- source file: /home/dima/swdb/swdb_all_data/swdb_all_data_unziped/USA_1998/Hist1998_SITEDESC.txt
-- region: USA, year: 1998

CREATE TABLE usa_1998_hist1998_sitedesc (
    siteid       text,
    ref          text,
    company      text,
    street       text,
    city         text,
    state        text,
    zipcode      text,
    street_mail  text,
    city_mail    text,
    state_mail   text,
    zipcode_mail text,
    phone        text,
    siccode      text,
    sicgroup     text,
    emple        text,
    reven        text,
    fiscl        text,
    govtlevel    text,
    remotes      text,
    domrem       text,
    intrem       text,
    sitedate     text,
    demodate     text,
    lastdate     text,
    dfref        text,
    language     text,
    msa          text,
    metro        text,
    cmsa         text,
    majormet     text,
    county       text,
    region       text,
    subregion    text,
    ziplong      text,
    ziplat       text,
    corpid       text,
    icorp        text,
    cindex       text,
    corphdq      text,
    homepageurl  text,
    source       text,
    naics        text,
    refid        text,
    totpc        text,
    totlan       text,
    totext       text,
    phone_sys    text,
    dfdark       text,
    teledark     text,
    sitetype     text,
    countrysort  text,
    filedate     text
);