-- source file: /home/dima/swdb/swdb_all_data/swdb_all_data_unziped/USA_1998/Hist1998_NET.txt
-- region: USA, year: 1998

CREATE TABLE usa_1998_hist1998_net (
    siteid      text,
    commdate    text,
    instlocs    text,
    planlocs    text,
    ilocs1      text,
    ilocs50     text,
    ilocs100    text,
    ilocs500    text,
    ilocs250i   text,
    plocs1      text,
    plocs50     text,
    plocs100    text,
    plocs500    text,
    plocs250i   text,
    insttrunk   text,
    instddd     text,
    inst800     text,
    instwats    text,
    inst900     text,
    insttie     text,
    instisdn    text,
    instt1      text,
    instt3      text,
    instft1     text,
    instft3     text,
    instfiber   text,
    instcoax    text,
    instmicro   text,
    instsat     text,
    instradio   text,
    instlaser   text,
    instcell    text,
    snastatus   text,
    tcpstatus   text,
    decnetstat  text,
    ipxstatus   text,
    appltlkstat text,
    osistatus   text,
    vinesipstat text,
    netbiosstat text,
    x25status   text,
    pppstatus   text,
    othprotstat text,
    protfill    text,
    vpnstatus   text,
    netpurch    text,
    prvnetpurch text,
    datacompur  text,
    instpriv    text,
    planpriv    text
);