-- source file: /home/dima/swdb/swdb_all_data/swdb_all_data_unziped/USA_1999/Hist1999_SITEDESC.txt
-- region: USA, year: 1999

CREATE TABLE usa_1999_hist1999_sitedesc (
    siteid       text,
    company      text,
    street       text,
    city         text,
    state        text,
    zipsector    text,
    zip7         text,
    zipcode      text,
    street_mail  text,
    city_mail    text,
    state_mail   text,
    zipcode_mail text,
    country      text,
    areacode     text,
    acexch       text,
    phone        text,
    sickey       text,
    sic3         text,
    siccode      text,
    sicgrp       text,
    naics3       text,
    naics        text,
    emple        text,
    reven        text,
    fiscl        text,
    govtlevel    text,
    sitedate     text,
    demodate     text,
    lastdate     text,
    language     text,
    msa          text,
    metro        text,
    cmsa         text,
    majormet     text,
    nuts4        text,
    county       text,
    region       text,
    subregion    text,
    ziplong      text,
    ziplat       text,
    corpid       text,
    entempl      text,
    corphdq      text,
    homepageurl  text,
    stype        text,
    refid        text,
    xref_id      text
);