-- source file: /home/dima/swdb/swdb_all_data/swdb_all_data_unziped/USA_1999/Hist1999_COMM.txt
-- region: USA, year: 1999

CREATE TABLE usa_1999_hist1999_comm (
    siteid         text,
    commdate       text,
    telesyspurch   text,
    longdispurch   text,
    totext         text,
    callcenter     text,
    telecallers    text,
    pbxstatus      text,
    coswstatus     text,
    centrexstatus  text,
    keystatus      text,
    singlnestatus  text,
    unspphnstatus  text,
    ldexp          text,
    ldout          text,
    ldin           text,
    ldintl         text,
    lddom          text,
    ldoutexp       text,
    ldinexp        text,
    ldtotintexp    text,
    ldtotdomexp    text,
    remotes        text,
    tottrunk       text,
    totddd         text,
    tot800         text,
    tottie         text,
    tottiepriv     text,
    tottieded      text,
    totisdn        text,
    tott1          text,
    tott3          text,
    totxdsl        text,
    totdata        text,
    maxdatacom     text,
    totcell        text,
    privnet_status text,
    vpn_status     text,
    netpurch       text
);