-- source file: /home/dima/swdb/swdb_all_data/swdb_all_data_unziped/USA_2004/Hist2004_CORP.txt
-- region: USA, year: 2004

CREATE TABLE usa_2004_hist2004_corp (
    corpid       text,
    ccompany     text,
    cstreet      text,
    ccity        text,
    cstate       text,
    czipsector   text,
    czipcode     text,
    ccountry     text,
    ccountrycode text,
    careacode    text,
    cphone       text,
    corp_ticker  text,
    exchange     text,
    corptype     text,
    rank         text,
    corpemple    text,
    sales        text,
    cyear        text,
    cfiscl       text,
    csickey      text,
    csic3        text,
    csiccode     text,
    cnaics       text,
    cnaic3des    text,
    cnaic6des    text,
    csites       text,
    ctotsites    text,
    cenhsites    text,
    cmetro       text,
    cmajmetro    text,
    alttype      text,
    altrank      text,
    cdunsi       text,
    cinfousa     text,
    csic2des     text,
    corphpurl    text,
    corptr       text,
    ctotbranch   text,
    ctotdivhq    text,
    csicsubgroup text
);