-- source file: /home/dima/swdb/swdb_all_data/swdb_all_data_unziped/USA_2004/Hist2004_TRENDRDF.txt
-- region: USA, year: 2004

CREATE TABLE usa_2004_hist2004_trendrdf (
    siteid           text,
    timetotprt       text,
    timetotsystprt   text,
    timetotpc        text,
    timetotdesk      text,
    timetotport      text,
    timetotinsvr     text,
    timetotmain      text,
    timetotibmpcm    text,
    timetotnonibmpcm text,
    timetotmidrange  text,
    timetotas400     text,
    timetotwks       text,
    timetotnonpc     text,
    timetotpcserver  text,
    timetotserver    text,
    timetotlansvr    text,
    timetotlan       text,
    timetotnodes     text,
    timetotext       text,
    timeldexp        text,
    timetottrunk     text,
    timetotddd       text,
    timetot800       text,
    timetottie       text,
    timetottiepriv   text,
    timetottieded    text,
    timetotisdn      text,
    timetott1        text,
    timetott3        text,
    timetotxdsl      text,
    timetotdata      text,
    timetotemple     text,
    indtotprt        text,
    indtotpageprt    text,
    indtotpc         text,
    indtotinsvr      text,
    indtotmidrange   text,
    indtotwks        text,
    indtotserver     text,
    indtotlan        text,
    indtotnodes      text,
    indtotext        text,
    indldexp         text,
    indtotddd        text,
    indtotisdn       text,
    indtott1         text,
    indtott3         text,
    indtotstorage    text,
    indtotdasd       text,
    indtotlanhub     text,
    indtotrouter     text,
    plan50000        text
);